<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>9</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MagicOnion.Abstractions" Version="7.0.0-preview.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Shared.csproj" />
    </ItemGroup>

</Project>
